baseURL = 'https://owittnan.net/'
languageCode = 'en-us'
title = "Oscar's site"
subtitle = ""
copyright = "Oscar Wittams-Nangle"
theme = 'smol'

[markup.goldmark.renderer]
unsafe = true

[params]
subtitle = ""

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "wishlist"
name = "Wishlist"
url = "/wish/"
weight = 3

# [[menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 4

# [[menu.main]]
# identifier = "tags"
# name = "Tags"
# url = "/tags/"
# weight = 4

[[menu.footer]]
identifier = "mastodon"
name = "Mastodon"
url = "https://tech.lgbt/@owittnan"
weight = 4
[menu.footer.params]
rel = "me"